apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: proshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: aleksandarkoloski7/proshop-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: node-env
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: port
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: mongo-uri
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: jwt-secret